;====================================================================
; Main.asm file generated by Amirhosein Abbasi
;
; Created:   Wed Apr 11 2018
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================

Start:
      ; Write your code here
      ldi r16,0b00010000
      out DDRD , r16 
      ldi r17 , 0b01000000
      out PORTD , r17
      
Loop:
      in r21,0b00000000 ;counter
      in r18,PIND
      cpi r18,0b00000000
      breq loop_ten
      ldi r20 , 0b00000000
      out PORTD , r20
      rjmp  Loop
      
loop_ten: 
      ldi r20 , 0b00010000
      out PORTD , r20
      CALL DELAY 
      ldi r20 , 0b00000000
      out PORTD , r20
      CALL DELAY 
      cpi r21 , 0x09
      breq ten_loop_break
      inc r21 
      rjmp  loop_ten
     
ten_loop_break: 
     ldi r20 , 0b00000000
     out PORTD , r20
     rjmp loop

DELAY:
	ldi  r18, 6
	ldi  r19, 19
	ldi  r20, 174
L1:  
	 dec  r20
	 brne L1
	 dec  r19
	 brne L1
	 dec  r18
	 brne L1
    ret

;====================================================================
