;====================================================================
; Main.asm file generated by Amirhosein Abbasi
;
; Created:   Wed Apr 11 2018
; Processor: ATmega16
; Compiler:  AVRASM (Proteus)
;====================================================================

;====================================================================
; DEFINITIONS
;====================================================================

;====================================================================
; VARIABLES
;====================================================================

;====================================================================
; RESET and INTERRUPT VECTORS
;====================================================================

      ; Reset Vector
      rjmp  Start

;====================================================================
; CODE SEGMENT
;====================================================================


Start:
      ; Write your code here
      ldi r21,0b00001111
      out WDTCR , r21
      ldi r16,0b00100000
      out DDRD , r16 
      ldi r17 , 0b01001000
      out PORTD , r17
      
Loop:
      in r18,PIND
      andi r18,0b00001000 ;check if click sw1
      cpi r18 , 0b00000000
      breq if_equal
      rjmp  Loop 
      
if_equal: 
      CALL turn_on
      in r18,PIND
      andi r18,0b01000000 ;check if click sw2
      cpi r18,0b00000000
      breq thexx 
      rjmp  if_equal
thexx :
      WDR ;watchdog timer reset
      rjmp if_equal
turn_on :
      ldi r20,0b00100000 
      out PORTD , r20
      ret
turn_off : 
      ldi r20,0b00000000 
      out PORTD , r20
      ret

;====================================================================
